// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $api_admin_create_user from "./routes/api/admin/create-user.ts";
import * as $api_admin_delete_user from "./routes/api/admin/delete-user.ts";
import * as $api_admin_list_users from "./routes/api/admin/list-users.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_mock_checkout from "./routes/api/mock-checkout.ts";
import * as $api_motherduck_token from "./routes/api/motherduck-token.ts";
import * as $api_onboarding_complete from "./routes/api/onboarding/complete.ts";
import * as $api_query_approve from "./routes/api/query/approve.ts";
import * as $api_user_context from "./routes/api/user/context.ts";
import * as $app_dashboard from "./routes/app/dashboard.tsx";
import * as $app_index from "./routes/app/index.tsx";
import * as $app_loading from "./routes/app/loading.tsx";
import * as $auth_signin from "./routes/auth/signin.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $health from "./routes/health.ts";
import * as $index from "./routes/index.tsx";
import * as $ContextSwitcher from "./islands/ContextSwitcher.tsx";
import * as $HeroFeature from "./islands/HeroFeature.tsx";
import * as $app_utils_ScrollToTop from "./islands/app_utils/ScrollToTop.tsx";
import * as $auth_AuthModal from "./islands/auth/AuthModal.tsx";
import * as $auth_LoginFlow from "./islands/auth/LoginFlow.tsx";
import * as $charts_AutoChart from "./islands/charts/AutoChart.tsx";
import * as $charts_FunnelChart from "./islands/charts/FunnelChart.tsx";
import * as $dashboard_smarter_dashboard_CacheManagementModal from "./islands/dashboard/smarter_dashboard/CacheManagementModal.tsx";
import * as $dashboard_smarter_dashboard_SmartDashLoadingPage from "./islands/dashboard/smarter_dashboard/SmartDashLoadingPage.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_LandingOverview from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingOverview.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_LandingPageDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingPageDashboard.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_SessionDetailsDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/SessionDetailsDashboard.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_UserDetailsDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/UserDetailsDashboard.tsx";
import * as $dashboard_smarter_dashboard_semantic_dashboard_AutoVisualizationExperience from "./islands/dashboard/smarter_dashboard/semantic_dashboard/AutoVisualizationExperience.tsx";
import * as $dashboard_smarter_dashboard_semantic_dashboard_SavedQueries from "./islands/dashboard/smarter_dashboard/semantic_dashboard/SavedQueries.tsx";
import * as $dashboard_starter_dashboard_BaseDashboardWizard from "./islands/dashboard/starter_dashboard/BaseDashboardWizard.tsx";
import * as $dashboard_starter_dashboard_FieldCatalog from "./islands/dashboard/starter_dashboard/FieldCatalog.tsx";
import * as $dashboard_starter_dashboard_WebDataRocksPivot from "./islands/dashboard/starter_dashboard/WebDataRocksPivot.tsx";
import * as $dashboard_starter_dashboard_data_utils from "./islands/dashboard/starter_dashboard/data-utils.ts";
import * as $onboarding_DashboardRouter from "./islands/onboarding/DashboardRouter.tsx";
import * as $onboarding_PlanSelection from "./islands/onboarding/PlanSelection.tsx";
import * as $onboarding_SignupFlow from "./islands/onboarding/SignupFlow.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/api/admin/create-user.ts": $api_admin_create_user,
    "./routes/api/admin/delete-user.ts": $api_admin_delete_user,
    "./routes/api/admin/list-users.ts": $api_admin_list_users,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/mock-checkout.ts": $api_mock_checkout,
    "./routes/api/motherduck-token.ts": $api_motherduck_token,
    "./routes/api/onboarding/complete.ts": $api_onboarding_complete,
    "./routes/api/query/approve.ts": $api_query_approve,
    "./routes/api/user/context.ts": $api_user_context,
    "./routes/app/dashboard.tsx": $app_dashboard,
    "./routes/app/index.tsx": $app_index,
    "./routes/app/loading.tsx": $app_loading,
    "./routes/auth/signin.tsx": $auth_signin,
    "./routes/checkout.tsx": $checkout,
    "./routes/health.ts": $health,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ContextSwitcher.tsx": $ContextSwitcher,
    "./islands/HeroFeature.tsx": $HeroFeature,
    "./islands/app_utils/ScrollToTop.tsx": $app_utils_ScrollToTop,
    "./islands/auth/AuthModal.tsx": $auth_AuthModal,
    "./islands/auth/LoginFlow.tsx": $auth_LoginFlow,
    "./islands/charts/AutoChart.tsx": $charts_AutoChart,
    "./islands/charts/FunnelChart.tsx": $charts_FunnelChart,
    "./islands/dashboard/smarter_dashboard/CacheManagementModal.tsx":
      $dashboard_smarter_dashboard_CacheManagementModal,
    "./islands/dashboard/smarter_dashboard/SmartDashLoadingPage.tsx":
      $dashboard_smarter_dashboard_SmartDashLoadingPage,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingOverview.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_LandingOverview,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingPageDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_LandingPageDashboard,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/SessionDetailsDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_SessionDetailsDashboard,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/UserDetailsDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_UserDetailsDashboard,
    "./islands/dashboard/smarter_dashboard/semantic_dashboard/AutoVisualizationExperience.tsx":
      $dashboard_smarter_dashboard_semantic_dashboard_AutoVisualizationExperience,
    "./islands/dashboard/smarter_dashboard/semantic_dashboard/SavedQueries.tsx":
      $dashboard_smarter_dashboard_semantic_dashboard_SavedQueries,
    "./islands/dashboard/starter_dashboard/BaseDashboardWizard.tsx":
      $dashboard_starter_dashboard_BaseDashboardWizard,
    "./islands/dashboard/starter_dashboard/FieldCatalog.tsx":
      $dashboard_starter_dashboard_FieldCatalog,
    "./islands/dashboard/starter_dashboard/WebDataRocksPivot.tsx":
      $dashboard_starter_dashboard_WebDataRocksPivot,
    "./islands/dashboard/starter_dashboard/data-utils.ts": $dashboard_starter_dashboard_data_utils,
    "./islands/onboarding/DashboardRouter.tsx": $onboarding_DashboardRouter,
    "./islands/onboarding/PlanSelection.tsx": $onboarding_PlanSelection,
    "./islands/onboarding/SignupFlow.tsx": $onboarding_SignupFlow,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
