// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_motherduck_token from "./routes/api/motherduck-token.ts";
import * as $api_onboarding_complete from "./routes/api/onboarding/complete.ts";
import * as $api_query_approve from "./routes/api/query/approve.ts";
import * as $app_dashboard from "./routes/app/dashboard.tsx";
import * as $app_index from "./routes/app/index.tsx";
import * as $app_loading from "./routes/app/loading.tsx";
import * as $health from "./routes/health.ts";
import * as $index from "./routes/index.tsx";
import * as $app_utils_ScrollToTop from "./islands/app_utils/ScrollToTop.tsx";
import * as $charts_AutoChart from "./islands/charts/AutoChart.tsx";
import * as $charts_FunnelChart from "./islands/charts/FunnelChart.tsx";
import * as $dashboard_smarter_dashboard_CacheManagementModal from "./islands/dashboard/smarter_dashboard/CacheManagementModal.tsx";
import * as $dashboard_smarter_dashboard_SmartDashLoadingPage from "./islands/dashboard/smarter_dashboard/SmartDashLoadingPage.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_LandingOverview from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingOverview.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_LandingPageDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingPageDashboard.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_SessionDetailsDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/SessionDetailsDashboard.tsx";
import * as $dashboard_smarter_dashboard_dashboard_landing_view_UserDetailsDashboard from "./islands/dashboard/smarter_dashboard/dashboard_landing_view/UserDetailsDashboard.tsx";
import * as $dashboard_smarter_dashboard_semantic_dashboard_AutoVisualizationExperience from "./islands/dashboard/smarter_dashboard/semantic_dashboard/AutoVisualizationExperience.tsx";
import * as $dashboard_starter_dashboard_BaseDashboardWizard from "./islands/dashboard/starter_dashboard/BaseDashboardWizard.tsx";
import * as $dashboard_starter_dashboard_FieldCatalog from "./islands/dashboard/starter_dashboard/FieldCatalog.tsx";
import * as $dashboard_starter_dashboard_WebDataRocksPivot from "./islands/dashboard/starter_dashboard/WebDataRocksPivot.tsx";
import * as $dashboard_starter_dashboard_data_utils from "./islands/dashboard/starter_dashboard/data-utils.ts";
import * as $onboarding_DashboardRouter from "./islands/onboarding/DashboardRouter.tsx";
import * as $onboarding_PlanSelection from "./islands/onboarding/PlanSelection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/motherduck-token.ts": $api_motherduck_token,
    "./routes/api/onboarding/complete.ts": $api_onboarding_complete,
    "./routes/api/query/approve.ts": $api_query_approve,
    "./routes/app/dashboard.tsx": $app_dashboard,
    "./routes/app/index.tsx": $app_index,
    "./routes/app/loading.tsx": $app_loading,
    "./routes/health.ts": $health,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/app_utils/ScrollToTop.tsx": $app_utils_ScrollToTop,
    "./islands/charts/AutoChart.tsx": $charts_AutoChart,
    "./islands/charts/FunnelChart.tsx": $charts_FunnelChart,
    "./islands/dashboard/smarter_dashboard/CacheManagementModal.tsx":
      $dashboard_smarter_dashboard_CacheManagementModal,
    "./islands/dashboard/smarter_dashboard/SmartDashLoadingPage.tsx":
      $dashboard_smarter_dashboard_SmartDashLoadingPage,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingOverview.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_LandingOverview,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/LandingPageDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_LandingPageDashboard,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/SessionDetailsDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_SessionDetailsDashboard,
    "./islands/dashboard/smarter_dashboard/dashboard_landing_view/UserDetailsDashboard.tsx":
      $dashboard_smarter_dashboard_dashboard_landing_view_UserDetailsDashboard,
    "./islands/dashboard/smarter_dashboard/semantic_dashboard/AutoVisualizationExperience.tsx":
      $dashboard_smarter_dashboard_semantic_dashboard_AutoVisualizationExperience,
    "./islands/dashboard/starter_dashboard/BaseDashboardWizard.tsx":
      $dashboard_starter_dashboard_BaseDashboardWizard,
    "./islands/dashboard/starter_dashboard/FieldCatalog.tsx":
      $dashboard_starter_dashboard_FieldCatalog,
    "./islands/dashboard/starter_dashboard/WebDataRocksPivot.tsx":
      $dashboard_starter_dashboard_WebDataRocksPivot,
    "./islands/dashboard/starter_dashboard/data-utils.ts": $dashboard_starter_dashboard_data_utils,
    "./islands/onboarding/DashboardRouter.tsx": $onboarding_DashboardRouter,
    "./islands/onboarding/PlanSelection.tsx": $onboarding_PlanSelection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
